// Generated by scripts/prepare-gallery.mjs. Edit its catalogue and rerun to update.

export type GalleryCategoryId = 'six-seater' | 'couple' | 'four-seater' | 'sofas';

export type GalleryCategory = {
  id: GalleryCategoryId;
  label: string;
  description: string;
  coverId: string;
};

export type GalleryItem = {
  id: string;
  category: GalleryCategoryId;
  title: string;
  alt: string;
  width: number;
  height: number;
  image: string;
};

export const galleryCategories: GalleryCategory[] = [
  {
    "id": "six-seater",
    "label": "Six-seater sets",
    "description": "Larger dining tables, chairs and bench seating for shared meals.",
    "coverId": "six-seater-05"
  },
  {
    "id": "couple",
    "label": "Couple seating",
    "description": "Compact tables and seating arrangements for cafés and smaller spaces.",
    "coverId": "couple-03"
  },
  {
    "id": "four-seater",
    "label": "Four-seater sets",
    "description": "Everyday dining arrangements in a range of colours and table styles.",
    "coverId": "four-seater-06"
  },
  {
    "id": "sofas",
    "label": "Restaurant sofas",
    "description": "Booths, benches and sofa seating for comfortable dining spaces.",
    "coverId": "sofas-10"
  }
];

export const galleryItems: GalleryItem[] = [
  {
    "id": "six-seater-01",
    "category": "six-seater",
    "title": "Brown padded-chair dining set",
    "alt": "Dark wood-look rectangular table with brown padded chairs, viewed from above",
    "width": 720,
    "height": 484,
    "image": "/images/gallery/six-seater-01.webp"
  },
  {
    "id": "six-seater-02",
    "category": "six-seater",
    "title": "Dark dining set",
    "alt": "Dark rectangular dining table with black padded chairs",
    "width": 720,
    "height": 506,
    "image": "/images/gallery/six-seater-02.webp"
  },
  {
    "id": "six-seater-03",
    "category": "six-seater",
    "title": "Table and bench set",
    "alt": "Light wood-look rectangular table with matching benches and black frames",
    "width": 720,
    "height": 522,
    "image": "/images/gallery/six-seater-03.webp"
  },
  {
    "id": "six-seater-04",
    "category": "six-seater",
    "title": "Dark tabletop with brown chairs",
    "alt": "Dark wood-look tabletop surrounded by brown padded dining chairs",
    "width": 720,
    "height": 530,
    "image": "/images/gallery/six-seater-04.webp"
  },
  {
    "id": "six-seater-05",
    "category": "six-seater",
    "title": "Wheel-base dining set",
    "alt": "Wood-look rectangular table with decorative wheel-shaped supports and black chairs",
    "width": 720,
    "height": 400,
    "image": "/images/gallery/six-seater-05.webp"
  },
  {
    "id": "couple-01",
    "category": "couple",
    "title": "Compact table and stools",
    "alt": "Square wood-look table with matching stools on black open frames",
    "width": 720,
    "height": 564,
    "image": "/images/gallery/couple-01.webp"
  },
  {
    "id": "couple-02",
    "category": "couple",
    "title": "Pink-accent café seating",
    "alt": "Small light tabletop on a pink base with pink and white chairs",
    "width": 720,
    "height": 525,
    "image": "/images/gallery/couple-02.webp"
  },
  {
    "id": "couple-03",
    "category": "couple",
    "title": "Square table with frame chairs",
    "alt": "Square light wood-look table with two black-frame chairs",
    "width": 720,
    "height": 682,
    "image": "/images/gallery/couple-03.webp"
  },
  {
    "id": "couple-04",
    "category": "couple",
    "title": "Compact black-chair dining sets",
    "alt": "Small light wood-look tables paired with black chairs in a dining space",
    "width": 720,
    "height": 878,
    "image": "/images/gallery/couple-04.webp"
  },
  {
    "id": "couple-05",
    "category": "couple",
    "title": "Red and white café seating",
    "alt": "Café interior with compact tables and red and white open-pattern chairs",
    "width": 720,
    "height": 397,
    "image": "/images/gallery/couple-05.webp"
  },
  {
    "id": "couple-06",
    "category": "couple",
    "title": "Colourful café corner",
    "alt": "Small café tables and brightly coloured chairs along a green wall",
    "width": 720,
    "height": 859,
    "image": "/images/gallery/couple-06.webp"
  },
  {
    "id": "four-seater-01",
    "category": "four-seater",
    "title": "Wood-look table with black chairs",
    "alt": "Rectangular wood-look tabletop with four black padded chairs",
    "width": 720,
    "height": 395,
    "image": "/images/gallery/four-seater-01.webp"
  },
  {
    "id": "four-seater-02",
    "category": "four-seater",
    "title": "Red-accent dining chairs",
    "alt": "Dark patterned tabletop with black chairs featuring red and white backrest panels",
    "width": 720,
    "height": 319,
    "image": "/images/gallery/four-seater-02.webp"
  },
  {
    "id": "four-seater-03",
    "category": "four-seater",
    "title": "Light table and bench seating",
    "alt": "Light wood-look table and matching bench seats with black rectangular frames",
    "width": 720,
    "height": 529,
    "image": "/images/gallery/four-seater-03.webp"
  },
  {
    "id": "four-seater-04",
    "category": "four-seater",
    "title": "Black and white dining set",
    "alt": "Dark patterned table with four black chairs with white backrest panels",
    "width": 720,
    "height": 321,
    "image": "/images/gallery/four-seater-04.webp"
  },
  {
    "id": "four-seater-05",
    "category": "four-seater",
    "title": "Pink padded-chair set",
    "alt": "Dark veined tabletop surrounded by four pink padded chairs with black frames",
    "width": 720,
    "height": 532,
    "image": "/images/gallery/four-seater-05.webp"
  },
  {
    "id": "four-seater-06",
    "category": "four-seater",
    "title": "Light tabletop with gold-tone chairs",
    "alt": "Light rectangular tabletop and four rounded-back chairs with gold-tone frames",
    "width": 720,
    "height": 434,
    "image": "/images/gallery/four-seater-06.webp"
  },
  {
    "id": "four-seater-07",
    "category": "four-seater",
    "title": "Golden table with wheel base",
    "alt": "Golden-coloured table with a decorative wheel base and black-frame chairs",
    "width": 720,
    "height": 521,
    "image": "/images/gallery/four-seater-07.webp"
  },
  {
    "id": "four-seater-08",
    "category": "four-seater",
    "title": "Cross-base dining table",
    "alt": "Wood-look table with crossed black legs and rounded-back chairs",
    "width": 720,
    "height": 523,
    "image": "/images/gallery/four-seater-08.webp"
  },
  {
    "id": "four-seater-09",
    "category": "four-seater",
    "title": "Wheel-base table arrangement",
    "alt": "Wood-look rectangular dining table with wheel-shaped supports and black chairs, side view",
    "width": 720,
    "height": 396,
    "image": "/images/gallery/four-seater-09.webp"
  },
  {
    "id": "four-seater-10",
    "category": "four-seater",
    "title": "White and blue dining set",
    "alt": "White dining table and white-frame chairs with bright blue seats",
    "width": 720,
    "height": 663,
    "image": "/images/gallery/four-seater-10.webp"
  },
  {
    "id": "four-seater-11",
    "category": "four-seater",
    "title": "Classic black-chair table set",
    "alt": "Wood-look dining table with wheel-shaped supports and black chairs, front view",
    "width": 720,
    "height": 390,
    "image": "/images/gallery/four-seater-11.webp"
  },
  {
    "id": "four-seater-12",
    "category": "four-seater",
    "title": "Restaurant dining layout",
    "alt": "Restaurant interior with rows of wood-look dining tables and black chairs",
    "width": 720,
    "height": 531,
    "image": "/images/gallery/four-seater-12.webp"
  },
  {
    "id": "four-seater-13",
    "category": "four-seater",
    "title": "Restaurant table arrangement",
    "alt": "A row of wood-look tables and black chairs in a restaurant dining room",
    "width": 720,
    "height": 840,
    "image": "/images/gallery/four-seater-13.webp"
  },
  {
    "id": "four-seater-14",
    "category": "four-seater",
    "title": "White tabletop with black chairs",
    "alt": "White rectangular tabletop on a black pedestal with four black chairs",
    "width": 720,
    "height": 519,
    "image": "/images/gallery/four-seater-14.webp"
  },
  {
    "id": "four-seater-15",
    "category": "four-seater",
    "title": "Blue café dining set",
    "alt": "Bright blue rectangular tabletop with four matching blue chairs",
    "width": 720,
    "height": 515,
    "image": "/images/gallery/four-seater-15.webp"
  },
  {
    "id": "four-seater-16",
    "category": "four-seater",
    "title": "Tall-back restaurant seating",
    "alt": "Square restaurant table with four tall-back brown chairs under coloured lighting",
    "width": 720,
    "height": 875,
    "image": "/images/gallery/four-seater-16.webp"
  },
  {
    "id": "four-seater-17",
    "category": "four-seater",
    "title": "Mixed-colour café chairs",
    "alt": "White rectangular tabletop with blue, yellow, black and red chairs",
    "width": 720,
    "height": 528,
    "image": "/images/gallery/four-seater-17.webp"
  },
  {
    "id": "four-seater-18",
    "category": "four-seater",
    "title": "Light wood-look dining set",
    "alt": "Light wood-look rectangular table with four tall black padded chairs",
    "width": 720,
    "height": 520,
    "image": "/images/gallery/four-seater-18.webp"
  },
  {
    "id": "four-seater-19",
    "category": "four-seater",
    "title": "Café seating arrangement",
    "alt": "Red and white open-pattern café chairs arranged around compact tables",
    "width": 720,
    "height": 390,
    "image": "/images/gallery/four-seater-19.webp"
  },
  {
    "id": "four-seater-20",
    "category": "four-seater",
    "title": "Round dark-top dining set",
    "alt": "Round dark tabletop with four silver-tone ladder-back chairs",
    "width": 720,
    "height": 315,
    "image": "/images/gallery/four-seater-20.webp"
  },
  {
    "id": "four-seater-21",
    "category": "four-seater",
    "title": "Colourful dining chairs in use",
    "alt": "People seated around a dark veined table with yellow and red padded chairs",
    "width": 720,
    "height": 507,
    "image": "/images/gallery/four-seater-21.webp"
  },
  {
    "id": "four-seater-22",
    "category": "four-seater",
    "title": "Yellow and red padded-chair set",
    "alt": "Dark veined tabletop with rounded yellow and red padded chairs",
    "width": 720,
    "height": 527,
    "image": "/images/gallery/four-seater-22.webp"
  },
  {
    "id": "four-seater-23",
    "category": "four-seater",
    "title": "Dark table with silver-tone chairs",
    "alt": "Dark rectangular tabletop paired with silver-tone ladder-back chairs",
    "width": 720,
    "height": 525,
    "image": "/images/gallery/four-seater-23.webp"
  },
  {
    "id": "four-seater-24",
    "category": "four-seater",
    "title": "Wraparound dining chair design",
    "alt": "Design image of a rounded square dark table with white and orange wraparound chairs",
    "width": 720,
    "height": 677,
    "image": "/images/gallery/four-seater-24.webp"
  },
  {
    "id": "sofas-01",
    "category": "sofas",
    "title": "Brown individual booth seats",
    "alt": "Rows of brown padded booth seats with tall backrests",
    "width": 720,
    "height": 942,
    "image": "/images/gallery/sofas-01.webp"
  },
  {
    "id": "sofas-02",
    "category": "sofas",
    "title": "Orange diamond-stitched seat",
    "alt": "Orange restaurant seat with a tall diamond-stitched backrest",
    "width": 716,
    "height": 1600,
    "image": "/images/gallery/sofas-02.webp"
  },
  {
    "id": "sofas-03",
    "category": "sofas",
    "title": "Black booth dining layout",
    "alt": "Restaurant tables paired with black button-detail booth benches",
    "width": 720,
    "height": 613,
    "image": "/images/gallery/sofas-03.webp"
  },
  {
    "id": "sofas-04",
    "category": "sofas",
    "title": "Orange booth seating row",
    "alt": "Four orange restaurant seats with tall diamond-stitched backrests arranged together",
    "width": 720,
    "height": 322,
    "image": "/images/gallery/sofas-04.webp"
  },
  {
    "id": "sofas-05",
    "category": "sofas",
    "title": "Black and yellow booth set",
    "alt": "Opposing black booth benches with yellow accents and a matching table",
    "width": 720,
    "height": 403,
    "image": "/images/gallery/sofas-05.webp"
  },
  {
    "id": "sofas-06",
    "category": "sofas",
    "title": "Grey tall-back bench",
    "alt": "Grey padded restaurant bench with a tall backrest on a dark frame",
    "width": 720,
    "height": 751,
    "image": "/images/gallery/sofas-06.webp"
  },
  {
    "id": "sofas-07",
    "category": "sofas",
    "title": "Café bench dining corner",
    "alt": "Brown padded café bench with an orange table and chairs against a green wall",
    "width": 720,
    "height": 491,
    "image": "/images/gallery/sofas-07.webp"
  },
  {
    "id": "sofas-08",
    "category": "sofas",
    "title": "Blue and yellow booth set",
    "alt": "Blue booth benches with yellow accents placed opposite each other around a table",
    "width": 720,
    "height": 506,
    "image": "/images/gallery/sofas-08.webp"
  },
  {
    "id": "sofas-09",
    "category": "sofas",
    "title": "Restaurant sofa design selection",
    "alt": "Reference collage showing restaurant sofa and bench designs in several colours",
    "width": 720,
    "height": 513,
    "image": "/images/gallery/sofas-09.webp"
  },
  {
    "id": "sofas-10",
    "category": "sofas",
    "title": "Blue diamond-stitched bench",
    "alt": "Blue restaurant bench with a tall diamond-stitched backrest",
    "width": 720,
    "height": 900,
    "image": "/images/gallery/sofas-10.webp"
  },
  {
    "id": "sofas-11",
    "category": "sofas",
    "title": "Red bench and chair arrangement",
    "alt": "Red restaurant bench and matching red chairs around a rectangular red table",
    "width": 720,
    "height": 516,
    "image": "/images/gallery/sofas-11.webp"
  },
  {
    "id": "sofas-12",
    "category": "sofas",
    "title": "Brown button-back bench",
    "alt": "Brown restaurant bench with a tall buttoned backrest",
    "width": 720,
    "height": 634,
    "image": "/images/gallery/sofas-12.webp"
  },
  {
    "id": "sofas-13",
    "category": "sofas",
    "title": "Tan straight-back bench seating",
    "alt": "Tan padded restaurant benches with plain straight backrests arranged in a row",
    "width": 720,
    "height": 515,
    "image": "/images/gallery/sofas-13.webp"
  },
  {
    "id": "sofas-14",
    "category": "sofas",
    "title": "Blue tall-back booth seat",
    "alt": "Deep blue restaurant bench with a tall plain backrest",
    "width": 720,
    "height": 903,
    "image": "/images/gallery/sofas-14.webp"
  },
  {
    "id": "sofas-15",
    "category": "sofas",
    "title": "Beige booth bench",
    "alt": "Beige padded booth bench with a plain tall backrest",
    "width": 720,
    "height": 530,
    "image": "/images/gallery/sofas-15.webp"
  },
  {
    "id": "sofas-16",
    "category": "sofas",
    "title": "Cream and brown booth seating",
    "alt": "A row of cream restaurant seats with dark brown backrest accents",
    "width": 720,
    "height": 319,
    "image": "/images/gallery/sofas-16.webp"
  },
  {
    "id": "sofas-17",
    "category": "sofas",
    "title": "Brown straight-back bench",
    "alt": "Brown padded restaurant bench with a tall straight backrest",
    "width": 720,
    "height": 527,
    "image": "/images/gallery/sofas-17.webp"
  },
  {
    "id": "sofas-18",
    "category": "sofas",
    "title": "Individual booth seat colours",
    "alt": "Individual restaurant booth seats displayed in brown, cream, pink, black and blue",
    "width": 720,
    "height": 306,
    "image": "/images/gallery/sofas-18.webp"
  },
  {
    "id": "sofas-19",
    "category": "sofas",
    "title": "Yellow restaurant benches",
    "alt": "Yellow restaurant benches with dark bases and stitched backrests",
    "width": 720,
    "height": 523,
    "image": "/images/gallery/sofas-19.webp"
  },
  {
    "id": "sofas-20",
    "category": "sofas",
    "title": "Brown diamond-button bench",
    "alt": "Brown restaurant bench with a diamond-pattern buttoned backrest",
    "width": 720,
    "height": 377,
    "image": "/images/gallery/sofas-20.webp"
  }
];
